# Buildpacks to include in builder
[[buildpacks]]
id = "spring-boot/spring-boot-test-info"
version = "0.0.3"
uri = "../buildpacks/test-info"

# Order used for detection
[[order]]
[[order.group]]
id = "spring-boot/spring-boot-test-info"
version = "0.0.3"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.stacks.jammy.tiny"
build-image = "ghcr.io/spring-projects/build-jammy-tiny:latest"
run-image = "ghcr.io/spring-projects/run-jammy-tiny:latest"

# Lifecycle executable version that will be used by the builder
[lifecycle]
version = "0.19.5"