spring:
  security:
    saml2:
      relyingparty:
        registration:
          simplesamlphp:
            signing:
              credentials:
                - private-key-location: "classpath:saml/privatekey.txt"
                  certificate-location: "classpath:saml/certificate.txt"
            assertingparty:
              verification:
                credentials:
                  - certificate-location: "classpath:saml/certificate.txt"
              entity-id: simplesaml
              singlesignon:
                url: https://simplesaml-for-spring-saml/SSOService.php
            relying-party-entity-id: "{baseUrl}/saml2/simple-relying-party"
          okta:
            signing:
              credentials:
                - private-key-location: "classpath:saml/privatekey.txt"
                  certificate-location: "classpath:saml/certificate.txt"
            assertingparty:
              verification:
                credentials:
                  - certificate-location: "classpath:saml/certificate.txt"
              entity-id: okta-id-1234
              singlesignon:
                url:
                  https://okta-for-spring/saml2/idp/SSOService.php

---

spring:
  config:
    activate:
      on-profile: "ssl-pem"
  ssl:
    bundle:
      pem:
        saml2:
          key:
            alias: "spring-boot"
            password: "secret"
          keystore:
            certificate: "classpath:saml/certificate.txt"
            private-key: "classpath:saml/privatekey.txt"
  security:
    saml2:
      relyingparty:
        registration:
          simplesamlphp:
            signing:
              credentials:
                - bundle:
                    name: "saml2"
                    alias: "spring-boot"
            assertingparty:
              verification:
                credentials:
                  - bundle:
                      name: "saml2"
                      alias: "spring-boot"
              entity-id: simplesaml
              singlesignon:
                url: https://simplesaml-for-spring-saml/SSOService.php
            relying-party-entity-id: "{baseUrl}/saml2/simple-relying-party"
          okta:
            signing:
              credentials:
                - bundle:
                    name: "saml2"
                    alias: "spring-boot"
            assertingparty:
              verification:
                credentials:
                  - bundle:
                      name: "saml2"
                      alias: "spring-boot"
              entity-id: okta-id-1234
              singlesignon:
                url:
                  https://okta-for-spring/saml2/idp/SSOService.php

---

spring:
  config:
    activate:
      on-profile: "ssl-jks"
  ssl:
    bundle:
      jks:
        saml2:
          key:
            alias: "spring-boot"
            password: "secret"
          keystore:
            location: "classpath:saml/test.p12"
            password: "secret"
  security:
    saml2:
      relyingparty:
        registration:
          simplesamlphp:
            signing:
              credentials:
                - bundle:
                    name: "saml2"
                    alias: "spring-boot"
            assertingparty:
              verification:
                credentials:
                  - bundle:
                      name: "saml2"
                      alias: "spring-boot"
              entity-id: simplesaml
              singlesignon:
                url: https://simplesaml-for-spring-saml/SSOService.php
            relying-party-entity-id: "{baseUrl}/saml2/simple-relying-party"
          okta:
            signing:
              credentials:
                - bundle:
                    name: "saml2"
                    alias: "spring-boot"
            assertingparty:
              verification:
                credentials:
                  - bundle:
                      name: "saml2"
                      alias: "spring-boot"
              entity-id: okta-id-1234
              singlesignon:
                url:
                  https://okta-for-spring/saml2/idp/SSOService.php
