name: Run Paketo Test
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  run-system-tests:
    name: 'Java ${{ matrix.java.version}}'
    runs-on: ubuntu-latest
    steps:
      - id: docker-info
        run: |
          docker info
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Prepare Gradle Build
        uses: ./.github/actions/prepare-gradle-build
        with:
          java-version: 17
          java-toolchain: false
      - name: Run Paketo Test
        id: run-paketo-test
        shell: bash
        run: |
          ./gradlew --no-daemon :spring-boot-system-tests:spring-boot-image-tests:systemTest --tests "org.springframework.boot.image.paketo.PaketoBuilderTests.executableJarApp"
      - name: Print JVM Thread Dumps When Cancelled
        uses: ./.github/actions/print-jvm-thread-dumps
        if: cancelled()
      - name: Print Docker Daemon Logs When Cancelled
        run: |
          journalctl -xu docker.service --since=today -n 50 --no-pager -overbose
        if: cancelled()
